#!/usr/bin/env bash
# display information about subdomains

domain_infos() {
    DOMAIN=$1
    SUB_DOMAIN=$2
    RECORD_TYPE=$(dig +noall +answer "$SUB_DOMAIN.$DOMAIN" | awk '{ print $4 }')
    DESTINATION_IP=$(dig +noall +answer "$SUB_DOMAIN.$DOMAIN" | awk '{ print $NF }')

    echo "The subdomain $SUB_DOMAIN is a $RECORD_TYPE record and points to $DESTINATION_IP"
}

if [ "$#" -eq 1 ]; then
    domain_infos "$1" "www"
    domain_infos "$1" "lb-01"
    domain_infos "$1" "web-01"
    domain_infos "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_infos "$1" "$2"
fi
