#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get -y update
sudo apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo 'Hello world!' | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
