#!/usr/bin/env bash
# Installs and configure HAproxy on my lb-01 server.

# Install HAproxy
sudo apt update
sudo apt-get install -y haproxy

# Let HAProxy be able to be managed using init script
sudo  echo "ENABLED=1" | sudo tee -a "/etc/default/haproxy"
sudo printf "\nlisten www\n\tbind :80\n\tmode http\n\tstats enable\n\tstats uri /haproxy?status\n\tbalance roundrobin\n\tserver 14266-web-01 18.204.56.40:80 check\n\tserver 14266-web-02 3.235.56.243:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
sudo service haproxy restart
