#!/usr/bin/env bash
#a Bash script that displays the time for 12 hours and 59 minutes:
hr=0
minute=1

while [ $hr -le 12 ]
do
  echo "Hour: $hr"

  while [ $minute -le 59 ]
  do
    echo $minute
    ((minute = minute + 1))
  done

  minute=1
  ((hr++))
done
